# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Xcode 16.1
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
      
    - name: Resolve Dependencies
      run: xcodebuild -resolvePackageDependencies

    - name: Build Project
      run: xcodebuild -scheme Foody -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1' build

    - name: Run Tests
      run: xcodebuild test -scheme Foody -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/reports/tests
